services:
  postgres:
    image: postgres:18.1
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - infra-network
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage
    restart: unless-stopped
    volumes:
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
      - ./garage.toml:/etc/garage.toml:ro
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "garage", "status"]
      interval: 15s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      STAGING_DOMAIN: ${STAGING_DOMAIN}
      PRODUCTION_DOMAIN: ${PRODUCTION_DOMAIN}
      STORAGE_DOMAIN: ${STORAGE_DOMAIN}
    networks:
      - infra-network
    depends_on:
      - garage

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - alloy_data:/var/lib/alloy/data
    environment:
      LOKI_URL: ${LOKI_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_PASSWORD: ${LOKI_PASSWORD}
      ALLOY_ENV: ${ALLOY_ENV}
    networks:
      - infra-network
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    # deploy:
    #   resources:
    #     limits:
    #       # Limit diturunkan ke 60M karena Alloy tidak lagi melakukan processing/parsing log yang berat
    #       memory: 60M 
    networks:
      - infra-network

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-infra}_postgres_data
  garage_meta:
    name: ${COMPOSE_PROJECT_NAME:-infra}_garage_meta
  garage_data:
    name: ${COMPOSE_PROJECT_NAME:-infra}_garage_data
  caddy_data:
    name: ${COMPOSE_PROJECT_NAME:-infra}_caddy_data
  caddy_config:
    name: ${COMPOSE_PROJECT_NAME:-infra}_caddy_config
  alloy_data:
    name: ${COMPOSE_PROJECT_NAME:-infra}_alloy_data

networks:
  infra-network:
    name: infra-network